chore: move classes to their own file
influxdata/influxdb-client-php pull request #68
Opened 2021-03-04 12:21 UTC by SMillerDev

## Proposed Changes

Since some IDEs have trouble dealing with multiple classes in a file, and it makes it easier for humans to find the class I suggest moving these classes to their own location.

## Checklist

- [ ] CHANGELOG.md updated
- [x] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `make test` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-03-04 12:28 UTC, bednar commented
@SMillerDev, Thanks for your PR 👍 We will take a look

2021-03-04 13:00 UTC, bednar requested changes
Thanks again for your PR 👍

Could you please update a `CHANGELOG.md` file? Something like:

```
### Bug Fixes
1. [#68](https://github.com/influxdata/influxdb-client-php/pull/68): Moved classes to their own file
```

2021-03-04 13:04 UTC, SMillerDev commented
✅

2021-03-05 08:50 UTC, bednar approved these changes

2021-03-05 08:50 UTC, merged